### PR TITLE
My favorite cats

### PR DESCRIPTION
**Pull request by andrewmtoy**
heres a markdown file that lists my favorite cats

### CODE REVIEW

**Comment by rileyhilliard** [comment]
@andrewmtoy Name this cat: 
dude

**Comment by andrewmtoy** [comment]
uh duh thats a Abyssinian

**Comment by andrewmtoy** [comment]
@brntbeer ready for pr

**Comment by rileyhilliard** [comment]
OK, ok, what about this one? 
cat

**Comment by andrewmtoy** [comment]
Thats obviously an Aegean

**Comment by rileyhilliard** [comment]
Idiot, this is clearly an Aegean
cat

**Comment by andrewmtoy** [comment]
this is true

**Comment by rileyhilliard** [comment]
- [x] This is a complete item
- [ ] This is an incomplete item

**Comment by rileyhilliard** [comment]
- [ ] This is a complete item
- [ ] This is an incomplete item
- [ ] This is a complete item
- [ ] This is an incomplete item
- [ ] This is a complete item
- [ ] This is an incomplete item
- [ ] This is a complete item
- [ ] This is an incomplete item

**Comment by githubteacher** [comment]
Such meta lists. :+1:

**Pull request merged**
